FROM mcr.microsoft.com/playwright:v1.40.0-jammy

WORKDIR /tests/e2e/playwright

COPY ./tests/e2e/playwright/package*.json ./tests/e2e/playwright/package-lock.json ./

RUN npm сi

COPY ./tests/e2e/playwright .

RUN npx playwright install --with-deps

ENTRYPOINT ["npx", "playwright", "test", "--project=chromium", "--config=./configs/playwright.config.ts"]
